### PR TITLE
Persist PIRStartState and  PIRStartSensitivity to DB

### PR DESCRIPTION
**Pull request by mliang2**
- persist `PIRStartState` and `PIRStartSensitivity` to database
- Log timestamp when `DeviceDB.persist` is called

### CODE REVIEW

**Comment by brianschrameck** [comment]
Thanks, @mliang2! I am just getting back from vacation, so give me some time to review and play with this.

**Comment by mliang2** [comment]
Here' how you can modify your exisiting sqlite  `arlo.db` to support the new fields

```
cp arlo.db arlo.db.bak  #backup db
sqlite3 arlo.db
alter table devices add column last_update integer;
alter table devices add column pir_start_sensitivity integer;
alter table devices add column pir_status text;
```

**Comment by brianschrameck** [comment]
@mliang2 I actually took a different tack with this: I decided to persist the entire `registerSet` message in the database for each camera. Any time *any* register is set, it will retrieve the current version from the DB, merge the change in, and store it back. It will then use this version from the DB instead of sending the default register set if the camera restarts. Check out the    [persist-register-sets](https://github.com/brianschrameck/arlo-cam-api/tree/persist-register-sets) branch; the only thing I have left is to handle the case when we only have a subset of registers set and the camera restarts (e.g. when you upgrade from a previous version of this code and you've already got cameras set up).

I'm going to close this PR in favor of that approach, but would welcome your feedback!

**Comment by brianschrameck** [comment]
#26 implements register set persistence

**Pull request closed without merging**
